CREATE USER symona IDENTIFIED BY symona;
GRANT CONNECT, RESOURCE, DBA TO symona;
GRANT CREATE SESSION symona;
GRANT UNLIMITED TABLESPACE TO symona;

CREATE USER syriusadm IDENTIFIED BY syrius;
GRANT CONNECT, RESOURCE, DBA TO syriusadm;
GRANT CREATE SESSION TO syriusadm;
GRANT UNLIMITED TABLESPACE TO syriusadm;

GRANT SELECT ON SYRIUSADM.BATCHLAUF TO SYMONA;
GRANT SELECT ON SYRIUSADM.BATCH TO SYMONA;




