CREATE USER symona IDENTIFIED BY symona;
GRANT CONNECT, RESOURCE, DBA TO symona;
GRANT CREATE SESSION TO symona;
GRANT UNLIMITED TABLESPACE TO symona;

CREATE USER syriusadm IDENTIFIED BY syrius;
GRANT CONNECT, RESOURCE, DBA TO syriusadm;
GRANT CREATE SESSION TO syriusadm;
GRANT UNLIMITED TABLESPACE TO syriusadm;

CREATE Table SYRIUSADM.Batch (
    PKEY NUMBER(12, 0) NOT NULL
  , BOID VARCHAR2(40 CHAR) NOT NULL
  , METABO NUMBER(12, 0) NOT NULL
  , LASTUPDATE TIMESTAMP(9) NOT NULL
  , PROCESSID VARCHAR2(40 CHAR) NOT NULL
  , ROWCOMMENT VARCHAR2(15 CHAR)
  , CREATED TIMESTAMP(9) NOT NULL
  , BIZCREATED TIMESTAMP(9) NOT NULL
  , CREATEDUSER VARCHAR2(40 CHAR) NOT NULL
  , BIZUSER VARCHAR2(40 CHAR)
  , REPLACED TIMESTAMP(9) NOT NULL
  , REPLACEDUSER VARCHAR2(40 CHAR)
  , GUELTAB DATE NOT NULL
  , GUELTBIS DATE NOT NULL
  , STATEFROM DATE NOT NULL
  , STATEUPTO DATE NOT NULL
  , STATEBEGIN DATE NOT NULL
  , STATEEND DATE NOT NULL
  , KURZBEZDT VARCHAR2(6 CHAR)
  , BEZEICHNUNGDT VARCHAR2(255 CHAR)
  , KURZBEZEN VARCHAR2(6 CHAR)
  , BEZEICHNUNGEN VARCHAR2(255 CHAR)
  , KURZBEZFR VARCHAR2(6 CHAR)
  , BEZEICHNUNGFR VARCHAR2(255 CHAR)
  , KURZBEZIT VARCHAR2(6 CHAR)
  , BEZEICHNUNGIT VARCHAR2(255 CHAR)
  , KURZBEZ05 VARCHAR2(6 CHAR)
  , BEZEICHNUNG05 VARCHAR2(255 CHAR)
  , KURZBEZ06 VARCHAR2(6 CHAR)
  , BEZEICHNUNG06 VARCHAR2(255 CHAR)
  , KURZBEZ07 VARCHAR2(6 CHAR)
  , BEZEICHNUNG07 VARCHAR2(255 CHAR)
  , KURZBEZ08 VARCHAR2(6 CHAR)
  , BEZEICHNUNG08 VARCHAR2(255 CHAR)
  , KURZBEZ09 VARCHAR2(6 CHAR)
  , BEZEICHNUNG09 VARCHAR2(255 CHAR)
  , KURZBEZ10 VARCHAR2(6 CHAR)
  , BEZEICHNUNG10 VARCHAR2(255 CHAR)
  , INTERNALNAME VARCHAR2(500 CHAR) NOT NULL
  , AKTIV VARCHAR2(40 CHAR) NOT NULL
  , PROGRAMM VARCHAR2(255 CHAR)
  , MAXNROFERRORS NUMBER(12, 0) NOT NULL
  , NROFTHREADS NUMBER(12, 0) NOT NULL
  , SQLMANID NUMBER(12, 0)
  , COLWIDTH VARCHAR2(200 CHAR)
  , ZUGRIFF VARCHAR2(40 CHAR)
  , HEADLINE VARCHAR2(2048 CHAR)
  , COLTYPE VARCHAR2(2048 CHAR)
  , SUMDEF VARCHAR2(200 CHAR)
  , TIMESEG DATE
  , ARCHIVETAG VARCHAR2(40 CHAR)
);

CREATE TABLE SYRIUSADM.BATCHLAUF
(
    PKEY NUMBER(12, 0) NOT NULL
  , BOID VARCHAR2(40 CHAR) NOT NULL
  , METABO NUMBER(12, 0) NOT NULL
  , LASTUPDATE TIMESTAMP(9) NOT NULL
  , PROCESSID VARCHAR2(40 CHAR) NOT NULL
  , ROWCOMMENT VARCHAR2(15 CHAR)
  , CREATED TIMESTAMP(9) NOT NULL
  , CREATEDUSER VARCHAR2(40 CHAR) NOT NULL
  , REPLACED TIMESTAMP(9) NOT NULL
  , REPLACEDUSER VARCHAR2(40 CHAR)
  , PREPROCESSOR VARCHAR2(255 CHAR)
  , FEEDER VARCHAR2(255 CHAR)
  , WORKER VARCHAR2(255 CHAR)
  , POSTVALIDATOR VARCHAR2(255 CHAR)
  , POSTPROCESSOR VARCHAR2(255 CHAR)
  , EXPORTER VARCHAR2(255 CHAR)
  , CLEANER VARCHAR2(255 CHAR)
  , BATCHLAUFINFO VARCHAR2(255 CHAR)
  , BLSTATUS VARCHAR2(40 CHAR)
  , STATE VARCHAR2(50 CHAR)
  , NUMBEROFWORKITEMS NUMBER(12, 0)
  , RETURNVALUETRANS NUMBER(12, 0)
  , RETURNVALUE NUMBER(12, 0)
  , STARTED DATE
  , STOPPED DATE
  , RMI_LOCATION VARCHAR2(100 CHAR)
  , SCHEDULE_SEQUENCE NUMBER(12, 0)
  , SCHEDULE_PAYLOAD VARCHAR2(255 CHAR)
  , ABHAENGIG VARCHAR2(40 CHAR) NOT NULL
  , CREATOR VARCHAR2(20 CHAR)
  , ITSBATCHLAUFBATCH VARCHAR2(40 CHAR) NOT NULL
  , ITSBATCHSCHEDULE VARCHAR2(40 CHAR)
  , INSTANZINFO VARCHAR2(400 CHAR)
  , THREADS NUMBER(12, 0)
  , MAXNROFERRORS NUMBER(12, 0)
  , MAXNROFFAILEDITEMS NUMBER(12, 0)
  , TIMESEG DATE
  , ARCHIVETAG VARCHAR2(40 CHAR)
);


GRANT SELECT ON SYRIUSADM.BATCHLAUF TO SYMONA;
GRANT SELECT ON SYRIUSADM.BATCH TO SYMONA;


